### PR TITLE
check for all artifact URLs return by coursier, if they exists.

### LINKED ISSUE #1403: PRs with broken urls
Hello there,

Today i saw a PR (repo is private so can't give a link) where urls were broken. So i was wondering if we can use `ExistenceClient` to check urls returned by `CoursierAlg.getArtifactIdUrlMapping` and either filter the ones with broken url out or show them as text (instead of link).

WDYT?

### PR DESCRIPTION
**Pull request by mzuehlke**
Include them only in the PR, if they exist.

( I didn't perform the filtering before generating the release related URLs. But I'm not sure about that)

fixes #1403

### CODE REVIEW

File: modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala [hunk 1]
```diff
@@ -153,10 +154,11 @@ final class NurtureAlg[F[_]](
         .traverse(vcsExtraAlg.getReleaseRelatedUrls(_, data.update))
       branchName = vcs.createBranch(config.vcsType, data.fork, data.update)
       migrations = migrationAlg.findMigrations(data.update)
+      existingArtifactUrls <- artifactIdToUrl.toList.filterA(a => existenceClient.exists(a._2))
```
Comment (kiranbayram) [inline modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala:157]: I think we shouldn't filter out the whole artifact when url is broken. We can still write the artifact id in PR body but as regular text instead of a url.

Comment (mzuehlke) [reply modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala:157]: When there is no URL for an `artifactId` we write the `artifactId` without the URL:
https://github.com/fthomas/scala-steward/blob/master/modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala#L121-L124

Comment (kiranbayram) [reply modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala:157]: Oh i see, i wasn't aware of that 👍

**Comment by fthomas** [comment]
Thanks for the PR, @mzuehlke!

If the filtering would be done before trying to find release related URLs, we could save a lot of calls to `HttpExistenceClient.exists` with URLs that most certainly do not exist. The URL from Coursier is the source URL from which we derive the release related URLs. If the source URL does not exists, I would expect that none of the derived URLs exist either.

**Comment by mzuehlke** [comment]
I agree and changed the PR to perform the check before generating release related URLs.
